# Generated by Django 2.2.2 on 2020-11-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('es_profesor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('enseñanza', models.CharField(max_length=15)),
                ('grado', models.CharField(max_length=30)),
                ('letra', models.CharField(max_length=15)),
                ('profesor_jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id_alumno', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('año_cursado', models.CharField(max_length=30)),
                ('asistencia', models.IntegerField()),
                ('comuna', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('enseñanza', models.CharField(max_length=30)),
                ('grado', models.CharField(max_length=30)),
                ('letra_curso', models.CharField(max_length=30)),
                ('promedio_general', models.FloatField()),
                ('rbd', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.curso')),
            ],
        ),
    ]
